[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  functionsPort = 8888
  targetPort = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"